/**
 * lib/posts.ts
 *
 * Content is loaded from a pre-generated JSON bundle (src/data/posts-generated.json)
 * instead of reading from the filesystem at runtime. This makes the module
 * compatible with Cloudflare Workers, where no filesystem exists.
 *
 * The JSON is regenerated by scripts/build-posts-data.mjs before every build.
 */

import postsData from '@/data/posts-generated.json';

export interface FaqItem {
  q: string;
  a: string;
}

export interface PostFrontmatter {
  title: string;
  slug: string;
  date: string;
  category: string;
  excerpt: string;
  coverImage: string;
  author: string;
  readTime: number;
  tags: string[];
  sources?: string[];
  coverAlt?: string;       // SEO-optimized alt text (falls back to title if absent)
  focusKeyword?: string;   // Primary SEO keyword for this article
  faq?: FaqItem[];         // Article-specific FAQ for Featured Snippets & GEO
}

export interface Post extends PostFrontmatter {
  content: string;
}

// Cast the imported JSON to our typed array
const posts = postsData as Post[];

export function getAllPosts(): PostFrontmatter[] {
  // Data is already sorted newest-first by the prebuild script
  return posts.map(({ content: _content, ...frontmatter }) => frontmatter as PostFrontmatter);
}

export function getPostBySlug(slug: string): Post | null {
  return posts.find((p) => p.slug === slug) ?? null;
}

export function getAllSlugs(): string[] {
  return posts.map((p) => p.slug);
}
